CREATE TABLE NODE (
   NODE_ID BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
   PLAYER TINYINT NOT NULL,
   CARDS BIGINT NOT NULL,
   HISTORY VARCHAR(1000) NOT NULL,
   ACTION_ID TINYINT NOT NULL,
   AMOUNT SMALLINT NOT NULL,
   REGRET INT NOT NULL DEFAULT 0,
   AVERAGE_ACTION SMALLINT NOT NULL,
   TOUCHED_SINCE_LAST_DISCOUNT SMALLINT UNSIGNED DEFAULT 0 NOT NULL,
   NUM_DISCOUNTS SMALLINT UNSIGNED DEFAULT 0 NOT NULL
);

CREATE INDEX QUERY_INDEX ON NODE(PLAYER, CARDS);

ALTER TABLE NODE
ADD COLUMN TOUCHED_SINCE_LAST_DISCOUNT SMALLINT UNSIGNED DEFAULT 0 NOT NULL,
ADD COLUMN NUM_DISCOUNTS SMALLINT UNSIGNED DEFAULT 0 NOT NULL,
MODIFY COLUMN PLAYER TINYINT NOT NULL,
MODIFY COLUMN CARDS BIGINT NOT NULL,
MODIFY COLUMN HISTORY VARCHAR(1000) NOT NULL,
MODIFY COLUMN ACTION_ID SMALLINT NOT NULL,
MODIFY COLUMN REGRET INT NOT NULL DEFAULT 0,
MODIFY COLUMN AVERAGE_ACTION SMALLINT NOT NULL DEFAULT 0;