CREATE TABLE NODE (
   PLAYER TINYINT,
   CARDS BIGINT,
   HISTORY VARCHAR(1000),
   ACTION_ID TINYINT,
   AMOUNT SMALLINT,
   REGRET INT,
   AVERAGE_ACTION SMALLINT
);

CREATE UNIQUE INDEX UNIQUE_INDEX ON NODE (PLAYER, CARDS, HISTORY(100), ACTION_ID, AMOUNT);

CREATE INDEX QUERY_INDEX ON NODE(PLAYER, CARDS);

WITH Primary key