DELIMITER //
CREATE PROCEDURE INSERT_OR_UPDATE_NODES(
    IN I_PLAYER TINYINT,
    IN I_CARDS BIGINT,
    IN I_HISTORY VARCHAR(1000),
    IN I_ACTION_ID TINYINT,
    IN I_AMOUNT SMALLINT,
    IN I_REGRET_CHANGE INT,
    IN I_AVERAGE_ACTION_CHANGE SMALLINT
    )
BEGIN
DECLARE NUM_NODES SMALLINT DEFAULT 0;
SELECT COUNT(*) INTO NUM_NODES FROM NODE WHERE
  PLAYER = I_PLAYER AND
  CARDS = I_CARDS AND
  HISTORY = I_HISTORY AND
  ACTION_ID = I_ACTION_ID AND
  AMOUNT = I_AMOUNT;
IF NUM_NODES > 0 THEN
    UPDATE NODE
    SET REGRET = REGRET + I_REGRET_CHANGE, AVERAGE_ACTION = AVERAGE_ACTION + I_AVERAGE_ACTION_CHANGE
    WHERE
        PLAYER = I_PLAYER AND
        CARDS = I_CARDS AND
        HISTORY = I_HISTORY AND
        ACTION_ID = I_ACTION_ID AND
        AMOUNT = I_AMOUNT;
ELSE
    INSERT INTO NODE (PLAYER, CARDS, HISTORY, ACTION_ID, AMOUNT, REGRET, AVERAGE_ACTION)
    VALUES (I_PLAYER, I_CARDS, I_HISTORY, I_ACTION_ID, I_AMOUNT, I_REGRET_CHANGE, I_AVERAGE_ACTION_CHANGE);
END IF;
END //

DELIMITER ;