DELIMITER //
CREATE PROCEDURE INSERT_OR_UPDATE_NODES(
    IN I_NODE_ID BIGINT,
    IN I_PLAYER TINYINT,
    IN I_CARDS BIGINT,
    IN I_HISTORY VARCHAR(1000),
    IN I_ACTION_ID TINYINT,
    IN I_AMOUNT SMALLINT,
    IN I_REGRET_CHANGE INT,
    IN I_AVERAGE_ACTION_CHANGE SMALLINT
    )
BEGIN

IF I_NODE_ID < 0 THEN
    INSERT INTO NODE (PLAYER, CARDS, HISTORY, ACTION_ID, AMOUNT, REGRET, AVERAGE_ACTION)
    VALUES (I_PLAYER, I_CARDS, I_HISTORY, I_ACTION_ID, I_AMOUNT, I_REGRET_CHANGE, I_AVERAGE_ACTION_CHANGE);
ELSE
    UPDATE NODE
    SET
        REGRET = IF (TOUCHED_SINCE_LAST_DISCOUNT >= 250, (REGRET + I_REGRET_CHANGE) * NUM_DISCOUNTS / (NUM_DISCOUNTS + 1), REGRET + I_REGRET_CHANGE),
        AVERAGE_ACTION = AVERAGE_ACTION + I_AVERAGE_ACTION_CHANGE,
        TOUCHED_SINCE_LAST_DISCOUNT = IF (TOUCHED_SINCE_LAST_DISCOUNT >= 250, 0, TOUCHED_SINCE_LAST_DISCOUNT + 1),
        NUM_DISCOUNTS = IF (TOUCHED_SINCE_LAST_DISCOUNT >= 250, NUM_DISCOUNTS + 1, NUM_DISCOUNTS)
    WHERE
            NODE_ID = I_NODE_ID;
END IF;
END //

DELIMITER ;