CREATE TABLE NODE (
   NODE_ID BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
   PLAYER TINYINT NOT NULL ,
   CARDS BIGINT NOT NULL,
   HISTORY VARCHAR(1000) NOT NULL,
   ACTION_ID TINYINT NOT NULL,
   AMOUNT SMALLINT NOT NULL,
   REGRET INT NOT NULL DEFAULT 0,
   AVERAGE_ACTION SMALLINT NOT NULL,
   TOUCHED_SINCE_LAST_DISCOUNT SMALLINT UNSIGNED DEFAULT 0 NOT NULL,
   NUM_DISCOUNTS SMALLINT UNSIGNED DEFAULT 0 NOT NULL
);

CREATE INDEX QUERY_INDEX ON NODE(PLAYER, CARDS);