DELIMITER //
CREATE PROCEDURE INSERT_OR_UPDATE_NODES(
    IN I_NODE_ID BIGINT,
    IN I_PLAYER TINYINT,
    IN I_CARDS BIGINT,
    IN I_HISTORY VARCHAR(1000),
    IN I_ACTION_ID TINYINT,
    IN I_AMOUNT SMALLINT,
    IN I_REGRET_CHANGE INT,
    IN I_AVERAGE_ACTION_CHANGE SMALLINT
    )
BEGIN

IF I_NODE_ID < 0 THEN
    INSERT INTO NODE (PLAYER, CARDS, HISTORY, ACTION_ID, AMOUNT, REGRET, AVERAGE_ACTION)
    VALUES (I_PLAYER, I_CARDS, I_HISTORY, I_ACTION_ID, I_AMOUNT, I_REGRET_CHANGE, I_AVERAGE_ACTION_CHANGE);
ELSE
    UPDATE NODE
    SET REGRET = REGRET + I_REGRET_CHANGE, AVERAGE_ACTION = AVERAGE_ACTION + I_AVERAGE_ACTION_CHANGE
    WHERE
            NODE_ID = I_NODE_ID;
END IF;
END //

DELIMITER ;